INGREDIENTS_DATABASE_FILENAME = "tests/json_files/ingredients.json"

RECIPE_DATABASE_FILENAME = "tests/json_files/recipes.json"

SHELF_LIST = [
    "FRUITS",
    "LEGUMES",
    "PAINS",
    "FRAIS",
    "SURGELES",
    "EPICERIE_SALEE",
    "EPICERIE_SUCREE",
    "BOISSONS",
]

INGREDIENT_TYPE = "INGREDIENTS"

RECIPE_TYPE = "RECIPES"

SHOPPING_LIST_TYPE = "SHOPPING_LIST"

TABLE_TYPE_LIST = [INGREDIENT_TYPE, RECIPE_TYPE]

INGREDIENTS_CATEGORIES = ["NOM", "RAYON", "PRIX", "CATEGORY", "UNITE"]

RECIPES_CATEGORIES = ["NOM INGREDIENT", "QUANTITE"]

SHOPPING_LIST_CATEGORIES = ["NOM", "RAYON", "QUANTITE", "UNITE", "PRIX"]

EXCEL_COLUMNS = [
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",
]

RECIPE_NAME_EXCEL_CASE = "B1"

TITLE_CELL = "B1"

FIRST_INGREDIENT_ROW = 4

FROZEN_FOOD_CATEGORY = "FROZEN_FOOD"
MARKET_CATEGORY = "MARKET"
SUPERMARKET_CATEGORY = "SUPERMARKET"

CATEGORIES = (FROZEN_FOOD_CATEGORY, MARKET_CATEGORY, SUPERMARKET_CATEGORY)
