# Generated by Django 3.2 on 2023-02-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_generation', '0004_recipeingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='list_generation.RecipeIngredient'),
        ),
    ]
