# Generated by Django 3.2 on 2023-02-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_generation', '0009_auto_20230208_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistgeneration',
            name='format_choice',
            field=models.CharField(choices=[('txt', 'txt'), ('pdf', 'pdf')], default='txt', max_length=3),
        ),
        migrations.AddField(
            model_name='shoppinglistgeneration',
            name='sending_method',
            field=models.CharField(choices=[('email', 'email'), ('download', 'download')], default='email', max_length=10),
        ),
    ]
