# Generated by Django 3.2 on 2023-02-08 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list_generation', '0010_auto_20230208_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglistgeneration',
            name='shopping_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='list_generation.shoppinglist'),
        ),
    ]
