# Generated by Django 3.2 on 2023-02-08 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list_generation', '0011_alter_shoppinglistgeneration_shopping_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglistgeneration',
            name='shopping_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list_generation.shoppinglist'),
        ),
    ]
