# Generated by Django 3.2 on 2023-02-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_generation', '0013_shoppingingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistgeneration',
            name='shopping_ingredients',
            field=models.ManyToManyField(to='list_generation.ShoppingIngredient'),
        ),
    ]
