# Generated by Django 3.2 on 2023-02-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_generation', '0014_shoppinglistgeneration_shopping_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglistgeneration',
            name='shopping_ingredients',
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='shopping_ingredients',
            field=models.ManyToManyField(to='list_generation.ShoppingIngredient'),
        ),
    ]
