# Generated by Django 3.2 on 2023-03-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_generation', '0015_auto_20230209_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistgeneration',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdf_files'),
        ),
    ]
